apiVersion: v1
kind: Pod
metadata:
  name: ambassador-example
spec:
  containers:
    # This is where the application container would go, for example
    # - name: nginx
    #   image: nginx
    # This is the ambassador container
    - name: twemproxy
      image: ganomede/twemproxy
      command: [ "nutcracker", "-c", "/etc/config/nutcracker.yaml", "-v", "7", "-s", "6222" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # This is the ConfigMap object we created using 'nutcracker.yaml'
        name: twem-config